// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Bingo struct {
	ID          int32
	Title       string
	Validfrom   pgtype.Timestamptz
	Validto     pgtype.Timestamptz
	Rows        pgtype.Int4
	Cols        pgtype.Int4
	Description pgtype.Text
	Codephrase  string
	Ready       bool
}

type BingosLogin struct {
	BingoID int32
	LoginID int32
}

type Login struct {
	ID           int32
	Name         string
	IsManagement bool
	Password     string
}

type Submission struct {
	ID      int32
	LoginID int32
	TileID  int32
	Date    pgtype.Timestamptz
	State   int32
}

type SubmissionComment struct {
	ID           int32
	Comment      string
	SubmissionID int32
	CreatedAt    pgtype.Timestamptz
	LoginID      int32
}

type SubmissionImage struct {
	ID           int32
	Path         string
	SubmissionID int32
}

type TemplateTile struct {
	ID          int32
	Title       string
	Imagepath   string
	Description string
}

type Tile struct {
	ID          int32
	Title       string
	Imagepath   string
	Description string
	BingoID     int32
}
